
clean:
	rm *.lint *.md

all:	addOrder.py.lint \
	AfricaLP.py.lint \
	AggCluster.py.lint \
	AvgNearestFacility.py.lint \
	AvgNearestFacility_sphericalDist.py.lint \
	AvgNearestGrid_polyline.py.lint \
	batchPrimsforTransformers.py.lint \
	batchPrims.py.lint \
	calcTree.py.lint \
	CMST_dfs.py.lint \
	DFS_BFD_Graph_Traversal.py.lint \
	distGen.py.lint \
	distStats.py.lint \
	FacilityLoc.py.lint \
	FacilityLoc_StarConfig.py.lint \
	fullTreeCalc.py.lint \
	genSubnets.py.lint \
	healthcarePrims.py.lint \
	HeurForMultiLevelNetwork.py.lint \
	kCluster.py.lint \
	KruskalCluster.py.lint \
	maxDist.py.lint \
	microgridDirectLV_improved.py.lint \
	MST.py.lint \
	PrimPenetrationRate.py.lint \
	SetCovering_WithNetwork.py.lint \
	SetCovering_withSphericalDistance_withPopandNames.py.lint \
	shapefile_editor.py.lint \
	TKruskals.py.lint \
	TPrims.py.lint \
	treeTrim.py.lint \
	modules-cluster.py.lint \
	modules-fileRWarcgis.py.lint \
	modules-fileRWogr.py.lint \
	modules-fileRW.py.lint \
	modules-kruskals.py.lint \
	modules-network.py.lint \
	modules-prims_neighborhood.py.lint \
	modules-prims.py.lint \
	modules-readCVSthenWRITE.py.lint \
	README.md

addOrder.py.lint:
	- pylint ../addOrder.py >addOrder.py.lint 2>&1
AfricaLP.py.lint:
	- pylint ../AfricaLP.py >AfricaLP.py.lint 2>&1
AggCluster.py.lint:
	- pylint ../AggCluster.py >AggCluster.py.lint 2>&1
AvgNearestFacility.py.lint:
	- pylint ../AvgNearestFacility.py >AvgNearestFacility.py.lint 2>&1
AvgNearestFacility_sphericalDist.py.lint:
	- pylint ../AvgNearestFacility_sphericalDist.py >AvgNearestFacility_sphericalDist.py.lint 2>&1
AvgNearestGrid_polyline.py.lint:
	- pylint ../AvgNearestGrid_polyline.py >AvgNearestGrid_polyline.py.lint 2>&1
batchPrimsforTransformers.py.lint:
	- pylint ../batchPrimsforTransformers.py >batchPrimsforTransformers.py.lint 2>&1
batchPrims.py.lint:
	- pylint ../batchPrims.py >batchPrims.py.lint 2>&1
calcTree.py.lint:
	- pylint ../calcTree.py >calcTree.py.lint 2>&1
CMST_dfs.py.lint:
	- pylint ../CMST_dfs.py >CMST_dfs.py.lint 2>&1
DFS_BFD_Graph_Traversal.py.lint:
	- pylint ../DFS_BFD_Graph_Traversal.py >DFS_BFD_Graph_Traversal.py.lint 2>&1
distGen.py.lint:
	- pylint ../distGen.py >distGen.py.lint 2>&1
distStats.py.lint:
	- pylint ../distStats.py >distStats.py.lint 2>&1
FacilityLoc.py.lint:
	- pylint ../FacilityLoc.py >FacilityLoc.py.lint 2>&1
FacilityLoc_StarConfig.py.lint:
	- pylint ../FacilityLoc_StarConfig.py >FacilityLoc_StarConfig.py.lint 2>&1
fullTreeCalc.py.lint:
	- pylint ../fullTreeCalc.py >fullTreeCalc.py.lint 2>&1
genSubnets.py.lint:
	- pylint ../genSubnets.py >genSubnets.py.lint 2>&1
healthcarePrims.py.lint:
	- pylint ../healthcarePrims.py >healthcarePrims.py.lint 2>&1
HeurForMultiLevelNetwork.py.lint:
	- pylint ../HeurForMultiLevelNetwork.py >HeurForMultiLevelNetwork.py.lint 2>&1
kCluster.py.lint:
	- pylint ../kCluster.py >kCluster.py.lint 2>&1
KruskalCluster.py.lint:
	- pylint ../KruskalCluster.py >KruskalCluster.py.lint 2>&1
maxDist.py.lint:
	- pylint ../maxDist.py >maxDist.py.lint 2>&1
microgridDirectLV_improved.py.lint:
	- pylint ../microgridDirectLV_improved.py >microgridDirectLV_improved.py.lint 2>&1
MST.py.lint:
	- pylint ../MST.py >MST.py.lint 2>&1
PrimPenetrationRate.py.lint:
	- pylint ../PrimPenetrationRate.py >PrimPenetrationRate.py.lint 2>&1
SetCovering_WithNetwork.py.lint:
	- pylint ../SetCovering_WithNetwork.py >SetCovering_WithNetwork.py.lint 2>&1
SetCovering_withSphericalDistance_withPopandNames.py.lint:
	- pylint ../SetCovering_withSphericalDistance_withPopandNames.py >SetCovering_withSphericalDistance_withPopandNames.py.lint 2>&1
shapefile_editor.py.lint:
	- pylint ../shapefile_editor.py >shapefile_editor.py.lint 2>&1
TKruskals.py.lint:
	- pylint ../TKruskals.py >TKruskals.py.lint 2>&1
TPrims.py.lint:
	- pylint ../TPrims.py >TPrims.py.lint 2>&1
treeTrim.py.lint:
	- pylint ../treeTrim.py >treeTrim.py.lint 2>&1
modules-cluster.py.lint:
	- pylint ../modules/cluster.py >modules-cluster.py.lint 2>&1
modules-fileRWarcgis.py.lint:
	- pylint ../modules/fileRWarcgis.py >modules-fileRWarcgis.py.lint 2>&1
modules-fileRWogr.py.lint:
	- pylint ../modules/fileRWogr.py >modules-fileRWogr.py.lint 2>&1
modules-fileRW.py.lint:
	- pylint ../modules/fileRW.py >modules-fileRW.py.lint 2>&1
modules-kruskals.py.lint:
	- pylint ../modules/kruskals.py >modules-kruskals.py.lint 2>&1
modules-network.py.lint:
	- pylint ../modules/network.py >modules-network.py.lint 2>&1
modules-prims_neighborhood.py.lint:
	- pylint ../modules/prims_neighborhood.py >modules-prims_neighborhood.py.lint 2>&1
modules-prims.py.lint:
	- pylint ../modules/prims.py >modules-prims.py.lint 2>&1
modules-readCVSthenWRITE.py.lint:
	- pylint ../modules/readCVSthenWRITE.py >modules-readCVSthenWRITE.py.lint 2>&1
 
addOrder.py.lint: ../addOrder.py
AfricaLP.py.lint: ../AfricaLP.py
AggCluster.py.lint: ../AggCluster.py
AvgNearestFacility.py.lint: ../AvgNearestFacility.py
AvgNearestFacility_sphericalDist.py.lint: ../AvgNearestFacility_sphericalDist.py
AvgNearestGrid_polyline.py.lint: ../AvgNearestGrid_polyline.py
batchPrimsforTransformers.py.lint: ../batchPrimsforTransformers.py
batchPrims.py.lint: ../batchPrims.py
calcTree.py.lint: ../calcTree.py
CMST_dfs.py.lint: ../CMST_dfs.py
DFS_BFD_Graph_Traversal.py.lint: ../DFS_BFD_Graph_Traversal.py
distGen.py.lint: ../distGen.py
distStats.py.lint: ../distStats.py
FacilityLoc.py.lint: ../FacilityLoc.py
FacilityLoc_StarConfig.py.lint: ../FacilityLoc_StarConfig.py
fullTreeCalc.py.lint: ../fullTreeCalc.py
genSubnets.py.lint: ../genSubnets.py
healthcarePrims.py.lint: ../healthcarePrims.py
HeurForMultiLevelNetwork.py.lint: ../HeurForMultiLevelNetwork.py
kCluster.py.lint: ../kCluster.py
KruskalCluster.py.lint: ../KruskalCluster.py
maxDist.py.lint: ../maxDist.py
microgridDirectLV_improved.py.lint: ../microgridDirectLV_improved.py
MST.py.lint: ../MST.py
PrimPenetrationRate.py.lint: ../PrimPenetrationRate.py
SetCovering_WithNetwork.py.lint: ../SetCovering_WithNetwork.py
SetCovering_withSphericalDistance_withPopandNames.py.lint: ../SetCovering_withSphericalDistance_withPopandNames.py
shapefile_editor.py.lint: ../shapefile_editor.py
TKruskals.py.lint: ../TKruskals.py
TPrims.py.lint: ../TPrims.py
treeTrim.py.lint: ../treeTrim.py
modules-cluster.py.lint: ../modules/cluster.py
modules-fileRWarcgis.py.lint: ../modules/fileRWarcgis.py
modules-fileRWogr.py.lint: ../modules/fileRWogr.py
modules-fileRW.py.lint: ../modules/fileRW.py
modules-kruskals.py.lint: ../modules/kruskals.py
modules-network.py.lint: ../modules/network.py
modules-prims_neighborhood.py.lint: ../modules/prims_neighborhood.py
modules-prims.py.lint: ../modules/prims.py
modules-readCVSthenWRITE.py.lint: ../modules/readCVSthenWRITE.py

README.md: *.lint
	echo "# Pylint scores as of `date +"%b %d %Y %H:%M:%S (UTC)" --utc` " > README.md
	echo "<table><tr><td><b>Script</b></td><td><b>Pylint Score</b></td></tr>" >> README.md 
	grep "Your code has been rated at" *.lint | sed -e 's/Your code has been rated at/ /' | sed -e 's/modules-/modules\//' | sed -e 's/^/<tr><td>/' | sed -e 's/\.lint:/<\/td><td align="right">/' | sed -e 's/$$/<\/td><\/tr>/' >> README.md
	echo "</table>" >> README.md

